# Generated by Django 5.0.6 on 2024-06-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('N/A', 'N/A'), ('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=12)),
                ('course', models.CharField(max_length=55)),
                ('year_level', models.IntegerField()),
                ('section', models.CharField(max_length=55)),
                ('semester', models.CharField(max_length=55)),
                ('ay', models.CharField(max_length=9)),
                ('classification', models.CharField(choices=[('N/A', 'N/A'), ('DROPPED', 'DROPPED'), ('REGULAR', 'REGULAR'), ('IRREGULAR', 'IRREGULAR')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='djangofinalproject.student')),
            ],
            options={
                'db_table': 'academic',
            },
        ),
    ]
